name: cloudflare_ai
description: This is a Dart package for Cloudflare AI. It provides a simple Dart API to interact with Cloudflare AI. It is built on top of the Dio package. It currently supports Text Generation and Image Generation, Text Summarization, and Image Generation Models. Feel free to contribute to this project through Issues and Pull Requests.
version: 1.0.0+2
repository: https://github.com/MananGandhi1810/cloudflare-ai-dart

environment:
  sdk: '>=2.18.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: