name: cloudflare_ai
description: This is a Dart package for Cloudflare Workers AI. It currently supports Text Generation and Image Generation, Text Summarization, and Image Generation Models.
version: 1.3.4
repository: https://github.com/MananGandhi1810/cloudflare-ai-dart

environment:
  sdk: '>=2.18.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: