# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_ACCOUNTID: ${{ secrets.ACCOUNTID }}
          ENV_APIKEY: ${{ secrets.APIKEY }}
          file-name: .env

      - name: Run tests
        run: dart test
